config/routes.rb
Rails.application.routes.draw do
  root 'task_manages#home'
  resources :tasks #do
  #  member do
  #    get :hoge
  #  end
  #end
  get '/index', to: 'tasks#index'
  get '/search', to: 'tasks#search'
  post '/search', to: 'tasks#search'
  #get '/new', to: 'tasks#new'
  #delete '/destroy', to: 'tasks#destroy'
  #get '/tasks/:id/edit', to: "tasks#edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/task_manages_controller.rb
class TaskManagesController < ApplicationController
  def home
    #render html: "Home"
  end

  def task_list
  end

  def new_task
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def index
    @tasks = Task.all
  end

  # 現状検索結果画面でブラウザをリロードすると死にます
  def search
    #binding.pry
    search_word = "content like '%" + params[:task][:content] + "%'"
    @tasks = Task.where(search_word)
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
    #binding.pry    
  end
 
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path
  end

  def update
    task = Task.find(params[:id])
    date = {
      year:   task_params["limit_date(1i)"].to_i,
      month:  task_params["limit_date(2i)"].to_i,
      day:    task_params["limit_date(3i)"].to_i,
      hour:   task_params["limit_date(4i)"].to_i,
      minute: task_params["limit_date(5i)"].to_i
      }
    task.update(
      content:    task_params[:content],
      status:     task_params[:status],
      limit_date: DateTime.new(
        date[:year],
        date[:month],
        date[:day],
        date[:hour],
        date[:minute]
        )
      )
      #binding.pry    
    if task.save
      redirect_to task
    else
      render 'update'
    end    
  end

  def create
    date = {
      year:   task_params["limit_date(1i)"].to_i,
      month:  task_params["limit_date(2i)"].to_i,
      day:    task_params["limit_date(3i)"].to_i,
      hour:   task_params["limit_date(4i)"].to_i,
      minute: task_params["limit_date(5i)"].to_i
      }
    task = Task.new(
      content:    task_params[:content],
      status:     task_params[:status],
      limit_date: DateTime.new(
        date[:year],
        date[:month],
        date[:day],
        date[:hour],
        date[:minute]
        )
      )
    #binding.pry
    
    if task.save
      redirect_to task
    else
      render 'new'
    end
  end

  private

    def task_params
      params.require(:task).permit(:content, :status, :limit_date)
      #binding.pry
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_manages_helper.rb
module TaskManagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Task Manager", root_url, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_url %></li>
            <li><%= link_to "タスク一覧", index_path %></li>
            <li><%= link_to "タスク追加", new_task_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/task_manages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home | Task Manage</title>
  </head>
  <body>
    <header>
      <% provide(:title, 'Home') %>
      <h1>Home</h1>
      <ul>
      <il><%= link_to "タスク一覧", index_path, class: "btn btn-lg btn-primary" %></li>
      <il><%= link_to "タスク追加", new_task_path, class: "btn btn-lg btn-primary" %></li>
      </ul>
    </header>
  </body>
</html>

app/views/task_manages/new_task.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスク追加 | Task Manage</title>
  </head>
  <body>  
    <header>
      <p>タスク追加</p>
      <ul>
        <li><%= link_to "Home", root_url%></li>
        <li><%= link_to "タスク一覧", task_list_path%></li>
      </ul>
    </header>
  </body>
</html>

app/views/task_manages/task_list.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスク一覧 | Task Manage</title>
  </head>
  <body>
    <header>
      <p>タスク一覧</p>
      <ul>
        <li><%= link_to "Home", root_url%></li>
        <li><%= link_to "タスク追加", new_task_path%></li>
      </ul>
    </header>
    <div>
      <ul>
        <li>hogehoge</li>
        <li>fugafuga</li>
        <li>hogefuga</li>
        <li>fugahoge</li>
      </ul>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスク編集 | Task Manage</title>
  </head>
  <body>
    <header>
      <% provide(:title, 'タスク編集') %>      
    </header>
    <div>
      <h1>タスク編集</h1>
      <h3>id：<%= @task.id %></h3>
      <h3>内容：<%= @task.content %></h3>
      <%= form_for @task do |f| %>
        <h3>ステータス：<%= f.select :status, [["未着手", "未着手"], ["着手", "着手"], ["完了", "完了"]] %></h3>
        <h3>期限：<%= f.datetime_select :limit_date %></h3>
        <h3><%= f.submit "編集" %></h3>
      <% end %>      
    </div>
  </body>
</html>

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスク一覧 | Task Manage</title>
  </head>
  <body>
    <header>
      <% provide(:title, 'タスク一覧') %>
    </header>
    <div>
    <h1>タスク一覧</h1>
      <% @tasks.each do |task| %>
        <ul>
          <h3><li><%= link_to task.content, task %></li></h3>
          <p>期限：<%= task.limit_date %></p>
        </ul>
      <% end %>
    </div>
  </body>
</html>

app/views/tasks/list.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスク一覧 | Task Manage</title>
  </head>
  <body>
    <header>
      <p>タスク一覧</p>
      <ul>
        <li><%= link_to "Home", root_url%></li>
        <li><%= link_to "タスク追加", new_path%></li>
      </ul>
    </header>
    <div>
    <h1>タスク一覧</h1>
      <% @task.each do |task| %>
        <ul>
          <li><%= task.content %></li>
        </ul>
      <% end %>
    </div>
  </body>
</html>

app/views/tasks/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスク追加 | Task Manage</title>
  </head>
  <body>  
    <header>
      <% provide(:title, 'タスク追加') %>
    </header>
    <div>
    <h1>タスク追加</h1>
      <%= form_for @task do |f| %>
        <h3>内容：<%= f.text_field :content %></h3>
        <h3>ステータス：<%= f.select :status, [["未着手", "未着手"], ["着手", "着手"], ["完了", "完了"]] %></h3>
        <h3>期限：<%= f.datetime_select :limit_date %></h3>
        <h3><%= f.submit "登録" %></h3>
      <% end %>
    </div>
  </body>
</html>

app/views/tasks/search.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスク一覧 | Task Manage</title>
  </head>
  <body>
    <%= form_tag search_path do %>
      <%= text_field :task, :content %>
      <%= submit_tag "検索" %>
    <% end %>
    <header>
      <% provide(:title, 'タスク一覧') %>
    </header>
    <div>
    <h1>タスク一覧</h1>
      <% @tasks.each do |task| %>
        <ul>
          <h3><li><%= link_to task.content, task %></li></h3>
          <p>期限：<%= task.limit_date %></p>
        </ul>
      <% end %>
    </div>
  </body>
</html>

app/views/tasks/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスク詳細 | Task Manage</title>
  </head>
  <body>
    <header>
      <% provide(:title, 'タスク詳細') %>      
    </header>
    <div>
      <h1>タスク詳細</h1>
      <h3>id：<%= @task.id %></h3>
      <h3>内容：<%= @task.content %></h3>
      <h3>ステータス：<%= @task.status %></h3>
      <h3>期限：<%= @task.limit_date %></h3>
      <h3><%= link_to "編集", edit_task_path %> | <%= link_to "削除", @task, method: :delete %></h3>
    </div>
  </body>
</html>